version: "3.9"

services:
  fhir-module:
    image: ghcr.io/bbmri-cz/fhir-module:latest
    container_name: fhir-module
    profiles:
      - dev
    networks:
      - fhir-integration
    restart: always
    environment:
      BLAZE_URL: "http://blaze:8080/fhir"
      DIR_PATH: "/opt/records"
    volumes:
      - type: bind
        source: "test/xml_data"
        target: "/opt/records"


  blaze:
    container_name: blaze
    image: "samply/blaze:0.22"
    networks:
      - fhir-integration
    profiles:
      - dev
    environment:
      BASE_URL: "http://localhost:8080"
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      LOG_LEVEL: "debug"
    ports:
      - "8080:8080"

networks:
  fhir-integration: