services:
  config-generator:
    image: alpine:latest
    entrypoint: /bin/sh
    command: -c "apk add --no-cache gettext && envsubst < /templates/prometheus.template.yml > /prometheus-config/prometheus.yml && envsubst < /templates/promtail-config.template.yaml > /promtail-config/promtail-config.yaml"
    volumes:
      - ./config/prometheus.template.yml:/templates/prometheus.template.yml:ro
      - ./config/promtail-config.template.yaml:/templates/promtail-config.template.yaml:ro
      - prometheus-config:/prometheus-config
      - promtail-config:/promtail-config
    env_file:
      - .env

  fhir-module:
    image: ghcr.io/bbmri-cz/fhir-module:latest
    container_name: fhir-module
    profiles:
      - dev
      - prod
    networks:
      - fhir-integration
      - monitoring
    restart: no
    ports:
      - "5001:5000"
    environment:
      BLAZE_URL: "http://test-blaze:8080/fhir"
      MIABIS_BLAZE_URL: "http://miabis-blaze:8080/fhir"
      MIABIS_ON_FHIR: "True"
      DIR_PATH: "/opt/records"
      PYTHONWARNINGS: "ignore:Unverified HTTPS request"
    volumes:
      - type: bind
        source: "test/xml_data"
        target: "/opt/records"
      - fhir-logs:/var/log/fhir-module

  fhir-ui:
    image: ghcr.io/bbmri-cz/fhir-ui:latest
    container_name: fhir-ui
    profiles:
      - ui
    networks:
      - fhir-integration
      - monitoring
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ui-data:/app/data
    depends_on:
      - fhir-module
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    profiles:
      - monitoring
    depends_on:
      config-generator:
        condition: service_completed_successfully
        required: false
    networks:
      - monitoring
    ports:
      - "9090:9090"
    volumes:
      - prometheus-config:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"

  miabis-blaze:
    container_name: miabis-blaze
    image: "samply/blaze:latest"
    networks:
      - fhir-integration
      - monitoring
    profiles:
      - dev
      - prod
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      DB_SEARCH_PARAM_BUNDLE: "/app/searchParamBundle.json"
      LOG_LEVEL: "debug"
    ports:
      - "5432:8080"
    volumes:
      - type: bind
        source: "util/searchParamBundle.json"
        target: "/app/searchParamBundle.json"

  test-blaze:
    container_name: test-blaze
    image: "samply/blaze:latest"
    networks:
      - fhir-integration
      - monitoring
    profiles:
      - dev
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      DB_SEARCH_PARAM_BUNDLE: "/app/searchParamBundle.json"
      LOG_LEVEL: "debug"
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: "util/searchParamBundle.json"
        target: "/app/searchParamBundle.json"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    profiles:
      - monitoring
    depends_on:
      config-generator:
        condition: service_completed_successfully
        required: false
    networks:
      - monitoring
    volumes:
      - fhir-logs:/var/log/fhir-module:ro
      - promtail-config:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yaml

networks:
  fhir-integration:
  monitoring:

volumes:
  prometheus_data:
  prometheus-config:
  fhir-logs:
  promtail-config:
  ui-data:
