services:
  fhir-module:
    image: ghcr.io/bbmri-cz/fhir-module:latest
    container_name: fhir-module
    profiles:
      - dev
      - prod
    networks:
      - fhir-integration
      - monitoring
    restart: no
    ports:
      - "5000:5000"
    environment:
      BLAZE_URL: "http://test-blaze:8080/fhir"
      MIABIS_BLAZE_URL: "http://miabis-blaze:8080/fhir"
      MIABIS_ON_FHIR: "True"
      DIR_PATH: "/opt/records"
      PYTHONWARNINGS: "ignore:Unverified HTTPS request"
    volumes:
      - type: bind
        source: "test/xml_data"
        target: "/opt/records"
      - fhir-logs:/var/log/fhir-module

  prometheus:
    image: prom/prometheus:latest
    profiles:
      - monitoring
    depends_on:
      config-generator:
        condition: service_completed_successfully
        required: false
    networks:
      - monitoring
    ports:
      - "9090:9090"
    volumes:
      - prometheus-config:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"

  miabis-blaze:
    container_name: miabis-blaze
    image: "samply/blaze:latest"
    networks:
      - fhir-integration
      - monitoring
    profiles:
      - dev
      - prod
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      DB_SEARCH_PARAM_BUNDLE: "/app/searchParamBundle.json"
      LOG_LEVEL: "debug"
    ports:
      - "5432:8080"
    volumes:
      - type: bind
        source: "util/searchParamBundle.json"
        target: "/app/searchParamBundle.json"

  test-blaze:
    container_name: test-blaze
    image: "samply/blaze:latest"
    networks:
      - fhir-integration
      - monitoring
    profiles:
      - dev
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      DB_SEARCH_PARAM_BUNDLE: "/app/searchParamBundle.json"
      LOG_LEVEL: "debug"
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: "util/searchParamBundle.json"
        target: "/app/searchParamBundle.json"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    profiles:
      - monitoring
    depends_on:
      config-generator:
        condition: service_completed_successfully
        required: false
    networks:
      - monitoring
    volumes:
      - fhir-logs:/var/log/fhir-module:ro
      - promtail-config:/etc/promtail
      - promtail-positions:/etc/promtail/positions
    command: -config.file=/etc/promtail/promtail-config.yaml
    restart: unless-stopped

networks:
  fhir-integration:
  monitoring:

volumes:
  prometheus_data:
  prometheus-config:
  fhir-logs:
  promtail-config:
  promtail-positions:
