services:
  fhir-module:
    image: ghcr.io/bbmri-cz/fhir-module:latest
    container_name: fhir-module
    profiles:
      - dev
      - prod
    networks:
      - fhir-integration
    restart: no
    environment:
      BLAZE_URL: "http://test-blaze:8080/fhir"
      MIABIS_BLAZE_URL: "http://miabis-blaze:8080/fhir"
      DIR_PATH: "/opt/records"
      PYTHONWARNINGS: "ignore:Unverified HTTPS request"
    volumes:
      - type: bind
        source: "test/xml_data"
        target: "/opt/records"



  miabis-blaze:
    container_name: miabis-blaze
    image: "samply/blaze:latest"
    networks:
      - fhir-integration
    profiles:
      - dev
      - prod
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      DB_SEARCH_PARAM_BUNDLE: "/app/searchParamBundle.json"
      LOG_LEVEL: "debug"
    ports:
      - "5432:8080"
    volumes:
      - type: bind
        source: "util/searchParamBundle.json"
        target: "/app/searchParamBundle.json"

  test-blaze:
    container_name: test-blaze
    image: "samply/blaze:latest"
    networks:
      - fhir-integration
    profiles:
      - dev
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      DB_SEARCH_PARAM_BUNDLE: "/app/searchParamBundle.json"
      LOG_LEVEL: "debug"
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: "util/searchParamBundle.json"
        target: "/app/searchParamBundle.json"

networks:
  fhir-integration:
