sonar.issue.ignore.multicriteria=e1,e2

# Disable *Mark the props of the component as read-only* error, since that is implicit for React
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S6759
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*

# Disable all for imported shadcn components
sonar.issue.ignore.multicriteria.e2.ruleKey=*
sonar.issue.ignore.multicriteria.e2.resourceKey=**/ui/fhir-place/src/components/ui/**/*