[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=100MB
logfile_backups=3
pidfile=/var/run/supervisord.pid
loglevel=info

[program:fhir-module]
command=gunicorn --preload -c gunicorn_config.py -w 1 -b 0.0.0.0:5000 main:app
directory=/opt/fhir-module
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/fhir-module/fhir-module.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=3
stderr_logfile=/var/log/fhir-module/fhir-module.error.log
stderr_logfile_maxbytes=100MB
stderr_logfile_backups=3
priority=1
environment=PROMETHEUS_MULTIPROC_DIR="/tmp/prometheus_multiproc"

[program:nextjs-ui]
command=node server.js
directory=/app
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/fhir-module/nextjs.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=3
stderr_logfile=/var/log/fhir-module/nextjs.error.log
stderr_logfile_maxbytes=100MB
stderr_logfile_backups=3
priority=2
environment=PORT="3000",HOSTNAME="0.0.0.0"


