[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
loglevel=info

[program:fhir-module]
command=gunicorn --preload -w 1 -b 0.0.0.0:5000 main:app
directory=/opt/fhir-module
user=nextjs
autostart=true
autorestart=true
stdout_logfile=/var/log/fhir-module/fhir-module.log
stderr_logfile=/var/log/fhir-module/fhir-module.error.log
priority=1

[program:nextjs-ui]
command=node server.js
directory=/app
user=nextjs
autostart=true
autorestart=true
stdout_logfile=/var/log/fhir-module/nextjs.log
stderr_logfile=/var/log/fhir-module/nextjs.error.log
priority=2
environment=PORT="3000",HOSTNAME="0.0.0.0"


