server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /etc/promtail/positions.yaml

clients:
  - url: "${GRAFANA_LOGS_URL}"
    basic_auth:
      username: "${GRAFANA_LOGS_USERNAME}"
      password: "${GRAFANA_LOGS_PASSWORD}"

scrape_configs:
  - job_name: fhir-module-sync
    static_configs:
      - targets: ["localhost"]
        labels:
          job: blaze
          environment: "${ENVIRONMENT}"
          __path__: /var/log/fhir-module/sync.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            sync_summary: sync_summary
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05,000"
      - labels:
          level:

  - job_name: fhir-module-miabis-sync
    static_configs:
      - targets: ["localhost"]
        labels:
          job: miabis-blaze
          environment: "${ENVIRONMENT}"
          __path__: /var/log/fhir-module/miabis_sync.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            sync_summary: sync_summary
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05,000"
      - labels:
          level:
